import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { SiteNavbar } from '@/components/site-navbar';
import { Web3Provider } from './web3-provider';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-slate-50 antialiased`}>
        <Web3Provider>
          <div className="min-h-screen">
            <SiteNavbar />
            <div className="pb-16 pt-6">{children}</div>
          </div>
        </Web3Provider>
      </body>
    </html>
  );
}
